const dummyTopicShopInfo = [
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
  },
];

export default dummyTopicShopInfo;
