const dummyShops = [
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
  {
    createdAt: "",
    genus: "",
    holiday: null,
    id: 1,
    location: "",
    map_id: "1724620019",
    shop_name: "",
    star_avg: null,
    total_review: null,
    updatedAt: "",
    work_time: "",
    x: "",
    y: "",
  },
];

export default dummyShops;
