const dummyShopInfo = [
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
  {
    address_name: null,
    category_group_code: null,
    category_group_name: null,
    category_name: null,
    distance: "",
    id: null,
    phone: null,
    place_name: null,
    place_url: null,
    road_address_name: null,
    x: null,
    y: null,
  },
];
export default dummyShopInfo;
