const dummyShopPics = [
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
  {
    createdAt: null,
    id: null,
    pic_URL: null,
    shop_id: null,
    updatedAt: null,
  },
];

export default dummyShopPics;
